#!/bin/bash

abspath() {
    if [ -d "$1" ]; then (cd "$1"; pwd)
    elif [ -f "$1" ]; then
        if [[ $1 = /* ]];     then echo "$1"
        elif [[ $1 == */* ]]; then echo "$(cd "${1%/*}"; pwd)/${1##*/}"
        else                       echo "$(pwd)/$1"; fi
    fi
}

MACOS_DIR=$(dirname "$0")
RES_DIR=$(abspath "$MACOS_DIR/../Resources")
"$RES_DIR/coordinator" -config="$RES_DIR"